[workspace]
resolver = "2"
members = ["crates/emoji-data", "crates/alfred-emoji", "xtask"]

[workspace.package]
version = "0.1.2"
edition = "2021"
license = "MIT"
authors = ["Micah Rosales"]
repository = "https://github.com/mrosales/alfred-emoji-rs"

[workspace.lints.rust]
unsafe_code = "deny"

[profile.release]
lto = true
strip = true
