[package]
name = "alfred-emoji"
description = "Alfred 5 script filter for emoji search"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "alfred-emoji"
path = "src/main.rs"

[dependencies]
emoji-data = { path = "../emoji-data" }
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = { version = "2", features = ["json"] }

[lints]
workspace = true
